Add docker compose arg test workflow
MonolithAILtd/.github pull request #25
Opened 2023-04-28 13:47 UTC by owenwaltonmono

Adds an optional boolean `docker_compose_test` input to test_image.yml workflow. This enables running a docker-compose-test.yml file which can contain any containers required when running the tests to be booted up.

It is not a required argument and has a `false` default so should not affect other workflows. Currently does not check whether there is a docker-compose-test.yml file, but should only be used by specific repos which have one e.g. teams, auth and dpu. These services have one which specifies a postgres DB container required when running some endpoint tests.

2023-05-01 09:20 UTC, McPonolith commented
I would prefer to have this ran as a pre-step to the general workflow. Rather than as a conditional. ie.

Test
----- docker compose up -f docker-compose.test.yml -d
----- run test workflow

2023-05-03 09:11 UTC, McPonolith commented
> > I would prefer to have this ran as a pre-step to the general workflow. Rather than as a conditional. ie.
> > Test ----- docker compose up -f docker-compose.test.yml -d ----- run test workflow
> 
> Do you mean putting it in it's own action file in the .github repo? I can give that a shot just wasn't sure if the process would remain running from the previous action into the subsequent test action.

No, i mean:
Theres is a workflow in lets say the "teams" service. This workflow calls this reusable workflow in an action. Before that action we should start the other containers. ie have it specified in the workflow of teams not .github repo

2023-05-03 12:51 UTC, owenwaltonmono commented
> > > I would prefer to have this ran as a pre-step to the general workflow. Rather than as a conditional. ie.
> > > Test ----- docker compose up -f docker-compose.test.yml -d ----- run test workflow
> > 
> > 
> > Do you mean putting it in it's own action file in the .github repo? I can give that a shot just wasn't sure if the process would remain running from the previous action into the subsequent test action.
> 
> No, i mean: Theres is a workflow in lets say the "teams" service. This workflow calls this reusable workflow in an action. Before that action we should start the other containers. ie have it specified in the workflow of teams not .github repo

So I think the issue with this is that, as far as I've read, it's not possible to specify all jobs in a workflow to execute on the same runner. Steps within a job will run on the same runner and so ensure that the containers are accessible for downstream steps. I think this restricts the solution to running it within the same job as a different step.

2023-05-03 13:05 UTC, McPonolith commented
> > > > I would prefer to have this ran as a pre-step to the general workflow. Rather than as a conditional. ie.
> > > > Test ----- docker compose up -f docker-compose.test.yml -d ----- run test workflow
> > > 
> > > 
> > > Do you mean putting it in it's own action file in the .github repo? I can give that a shot just wasn't sure if the process would remain running from the previous action into the subsequent test action.
> > 
> > 
> > No, i mean: Theres is a workflow in lets say the "teams" service. This workflow calls this reusable workflow in an action. Before that action we should start the other containers. ie have it specified in the workflow of teams not .github repo
> 
> So I think the issue with this is that, as far as I've read, it's not possible to specify all jobs in a workflow to execute on the same runner. Steps within a job will run on the same runner and so ensure that the containers are accessible for downstream steps. I think this restricts the solution to running it within the same job as a different step.

But i believe it is the same job no? Just another step?

2023-05-03 13:19 UTC, McPonolith commented
> > > > > I would prefer to have this ran as a pre-step to the general workflow. Rather than as a conditional. ie.
> > > > > Test ----- docker compose up -f docker-compose.test.yml -d ----- run test workflow
> > > > 
> > > > 
> > > > Do you mean putting it in it's own action file in the .github repo? I can give that a shot just wasn't sure if the process would remain running from the previous action into the subsequent test action.
> > > 
> > > 
> > > No, i mean: Theres is a workflow in lets say the "teams" service. This workflow calls this reusable workflow in an action. Before that action we should start the other containers. ie have it specified in the workflow of teams not .github repo
> > 
> > 
> > So I think the issue with this is that, as far as I've read, it's not possible to specify all jobs in a workflow to execute on the same runner. Steps within a job will run on the same runner and so ensure that the containers are accessible for downstream steps. I think this restricts the solution to running it within the same job as a different step.
> 
> But i believe it is the same job no? Just another step?

I believe I am incorrect. A re-usable workflow is called as an entire job not just a step in the job

2023-05-03 13:21 UTC, McPonolith requested changes

2023-05-03 13:21 UTC, McPonolith commented on .github/workflows/test_image.yml
> +        type: boolean
I think it would be best if we passed in the filename here as opposed to having it hardcoded.
We might also want to pass in additional commands here, instead of just the filename

2023-05-03 14:12 UTC, McPonolith requested changes

2023-05-03 14:12 UTC, McPonolith commented on .github/workflows/test_image.yml
> +      docker_compose_file:
maybe rename additional_docker_compose_file
additional_services etc .

Also wondering could we have utilised renaming the compose file to be the override file (I dont think we couldve, due to it being a different job)

2023-06-29 15:01 UTC, owenwaltonmono commented on .github/workflows/test_image.yml
> +        docker build . --ssh default --target '${{ inputs.stage }}' --network host
The `--network host` flag is required to allow any connections to services exposed on the host e.g. redis or any DBs required for tests to run.

2023-06-29 15:40 UTC, owenwaltonmono commented on .github/workflows/test_image.yml
> +        type: boolean
For the sake of security hardening, I have decided to limit the input to the filepath. Technically some flags could also be added to this, however I have tried to limit down the amount of potentially executable input.

2023-06-29 15:41 UTC, owenwaltonmono commented on .github/workflows/test_image.yml
> +      docker_compose_file:
I feel like this rename would be potentially confusing as to what the input is actually supposed to represent.

2023-06-29 16:08 UTC, merged